---
# This Playbook configure firewall 'ferm'
- name: Ferm | Install iptables
  package:
    name: iptables
    state: present

- name: Ferm | Install Ferm
  package:
    name: ferm
    state: present

- name: Ferm | Disable firewalls
  service: name="{{ item }}" state=stopped enabled=no
  with_items: "{{ disable_other_firewalls }}"
  ignore_errors: true

- name: Ferm | Display rules var
  debug: var=ferm_rules

- name: Ferm | Create config directory
  file: path="{{ferm_dir}}" state=directory owner=root group=root

- name: Ferm | Include ferm.d directory on non-RedHat
  lineinfile: dest=/etc/ferm/ferm.conf line="@include 'ferm.d/';" backup=yes insertbefore=BOF create=yes
  when: ansible_os_family|lower != "redhat"

- name: Ferm | Include ferm.d directory on RedHat
  lineinfile: dest=/etc/ferm.conf line="@include 'ferm.d/';" backup=yes insertbefore=BOF create=yes
  when: ansible_os_family|lower != "redhat"

- name: Ferm | Create the ferm conf files
  template: src=ferm.conf.j2 dest="{{ ferm_dir }}/{{item.key}}.conf" mode=0655 owner=root group=root backup=yes
  with_dict: "{{ ferm_rules }}"
  notify:
    - reload ferm

- meta: flush_handlers

- name: reload ferm
  service: name=ferm state=restarted
  changed_when: False
  register: fermreloaded

- name: enable ferm on boot
  service: name=ferm enabled=yes

- name: if ferm_fail2ban is True - restart fail2ban as well if ferm is reloaded
  service: name=fail2ban state=restarted
  when: fermreloaded.changed and ferm_fail2ban
